<?php View::flash(); ?>

<div class="container shell-view">

    <?php View::process($page_module, $page_title, $set_title); ?>

    <?php echo DwForm::open(); ?>

        <div class="row">
            <div class="col-md-4">
                <?php echo DwForm::text('agencia.nombre', array('class'=>'input-lower input-required'), $agencia->nombre, 'Nombre'); ?>
            </div>
            <div class="col-md-4">
                <?php echo DwForm::text('agencia.direccion', array('class'=>'input-lower input-required'), $agencia->direccion, 'Dirección'); ?>
            </div>
       	</div>     
        
        <div class="row">
        	<div class="col-md-4">
                <?php echo DwForm::select('agencia.activo', array(Agencias::ACTIVO => 'Activa', Agencias::INACTIVO => 'Bloqueada'), array('class'=>'input-lower input-required'), $agencia->activo, 'Estado'); ?>

            </div>
            
        </div>
    
        
        <div class="row">
            <div class="form-actions">
                <?php echo DwForm::send('Guardar agencia'); ?>
                <?php echo DwForm::cancel(); ?>
                <?php echo DwForm::focus('agencia.nombre'); ?>
            </div>
        </div>

    <?php echo DwForm::close(); ?>

</div>