<?php View::flash(); ?>

<script type="text/javascript">
    $(function() {
        $('table').kgrid({
			form_to: 	$.KumbiaPHP.publicPath+'administracion/ccostos/buscar/',
            order_to:   $.KumbiaPHP.publicPath+"administracion/ccostos/listar/",
            order_attr: '<?php echo (APP_AJAX) ? 'class="js-link js-spinner"' : ''; ?>'
        });
    });
</script>

<div class="container shell-view">
    
    <?php View::process($page_module, $page_title, $set_title); ?>
    
    <div class="btn-toolbar btn-toolbar-top">
        <div class="row">            
            <div class="btn-actions">
                <?php echo DwHtml::button("administracion/ccostos/agregar/", 'agregar ceco', NULL, 'fa-check-square-o', APP_AJAX); ?>
            </div>
        </div>
    </div>
    
    <div class="container-overflow">
    
        <table class="table table-bordered table-hover table-striped table-condensed table-responsive">
            <thead>
                <tr>
                    <th data-order="id">ID</th>
                    <th data-search="codigo" data-order="codigo">CODIGO</th>
                    <th data-search="nombre" data-order="nombre">NOMBRE</th>
                    <th data-order="activo">ESTADO</th>
                    <th class="btn-actions col-blocked text-center">ACCIONES</th>
                </tr>
            </thead>
            
           	<tbody>

                <?php foreach($ccostos->items as $ccosto): ?>
                	<?php $key_upd = Security::setKey($ccosto->id, 'upd_ccostos'); ?>
                    <?php $key_ina = Security::setKey($ccosto->id, 'inactivar_ccostos'); ?>
                    <?php $key_rea = Security::setKey($ccosto->id, 'reactivar_ccostos'); ?>
                    <?php $key_del = Security::setKey($ccosto->id, 'eliminar_ccostos'); ?> 
                    <tr>
                        <td><?php echo $ccosto->id; ?></td>
                        <td><?php echo $ccosto->codigo; ?></td>
                        <td><?php echo $ccosto->nombre; ?></td>
                        <td><?php echo ($ccosto->activo == Ccostos::ACTIVO) ? '<span class="label label-success">Activo</span>' : '<span class="label label-danger">Bloqueado</span>'; ; ?></td>
                        <td>
                                <?php echo DwHtml::buttonTable('Modificar ccostos', "administracion/ccostos/editar/$key_upd/", null, 'warning', 'fa-edit'); ?>
                                <?php if($ccosto->activo == Ccostos::ACTIVO) { ?>
                                    <?php echo DwHtml::buttonTable('Bloquear ccostos', "administracion/ccostos/estado/inactivar/$key_ina/", null, 'success', 'fa-flag'); ?>
                                <?php } else { ?>
                                    <?php echo DwHtml::buttonTable('Reactivar ccostos', "administracion/ccostos/reactivar/$key_rea/", null, 'danger', 'fa-flag'); ?>
                                <?php } ?>
                                <?php echo DwHtml::buttonTable('Eliminar ccostos', "administracion/ccostos/eliminar/$key_del/", array('class'=>'js-confirm', 'confirm-title'=>'Eliminar ccostos', 'confirm-body'=>'Está seguro de eliminar este centro de costo? <br />Recuerda que esta operación no se puede reversar.'), 'danger', 'fa-ban'); ?>
                            </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
        <?php View::partial('paginators/default', false, array('page'=>$ccostos, 'url'=>"administracion/ccostos/listar/$order/")); ?>
        
    </div>
  
    
</div>